//
//  Gear.swift
//  MySampleApp
//
//
// Copyright 2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-swift v0.21
//

import Foundation
import UIKit
import AWSDynamoDB

class Gear: AWSDynamoDBObjectModel, AWSDynamoDBModeling {
    
    var _gearId: String?
    var _kiteSize: NSNumber?
    var _boardBrand: String?
    var _boardSize: NSNumber?
    var _boardType: String?
    var _kiteBrand: String?
    var _kiteType: String?
    
    
    class func dynamoDBTableName() -> String {

        return "thekitelife-mobilehub-374752204-gear"
    }
    
    class func hashKeyAttribute() -> String {

        return "_gearId"
    }
    
    class func rangeKeyAttribute() -> String {

        return "_kiteSize"
    }
    
    override class func jsonKeyPathsByPropertyKey() -> [AnyHashable: Any] {
        return [
               "_gearId" : "gearId",
               "_kiteSize" : "kiteSize",
               "_boardBrand" : "boardBrand",
               "_boardSize" : "boardSize",
               "_boardType" : "boardType",
               "_kiteBrand" : "kiteBrand",
               "_kiteType" : "kiteType",
        ]
    }
}
