//
//  Kiter.swift
//  MySampleApp
//
//
// Copyright 2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-swift v0.21
//

import Foundation
import UIKit
import AWSDynamoDB

class Kiter: AWSDynamoDBObjectModel, AWSDynamoDBModeling {
    
    var _kiterId: String?
    var _kiterName: String?
    var _kiterBitmoji: String?
    
    class func dynamoDBTableName() -> String {

        return "thekitelife-mobilehub-374752204-kiter"
    }
    
    class func hashKeyAttribute() -> String {

        return "_kiterId"
    }
    
    class func rangeKeyAttribute() -> String {

        return "_kiterName"
    }
    
    override class func jsonKeyPathsByPropertyKey() -> [AnyHashable: Any] {
        return [
               "_kiterId" : "kiterId",
               "_kiterName" : "kiterName",
               "_kiterBitmoji" : "kiterBitmoji",
        ]
    }
}
