//
//  Session.swift
//  MySampleApp
//
//
// Copyright 2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-swift v0.21
//

import Foundation
import UIKit
import AWSDynamoDB

class Session: AWSDynamoDBObjectModel, AWSDynamoDBModeling {
    
    var _sessionID: String?
    var _date: String?
    var _active: NSNumber?
    var _gearID: String?
    var _kiterId: String?
    var _locationDataPointsIDs: Set<String>?
    var _spotID: String?
    var _spotTitle: String?
    var _windSpeedID: String?
    
    class func dynamoDBTableName() -> String {
        
        return "thekitelife-mobilehub-374752204-session"
    }
    
    class func hashKeyAttribute() -> String {
        
        return "_sessionID"
    }
    
    class func rangeKeyAttribute() -> String {
        
        return "_date"
    }
    
    override class func jsonKeyPathsByPropertyKey() -> [AnyHashable: Any] {
        return [
            "_sessionID" : "sessionID",
            "_date" : "date",
            "_active" : "active",
            "_gearID" : "gearID",
            "_kiterId" : "kiterId",
            "_locationDataPointsIDs" : "locationDataPointsIDs",
            "_spotID" : "spotID",
            "_spotTitle" : "spotTitle",
            "_windSpeedID" : "windSpeedID",
        ]
    }
}
