//
//  Spot.swift
//  MySampleApp
//
//
// Copyright 2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-swift v0.21
//

import Foundation
import UIKit
import AWSDynamoDB

class Spot: AWSDynamoDBObjectModel, AWSDynamoDBModeling {
    
    var _id: String?
    var _kiterId: String?
    var _title: String?
    var _difficulties: Set<String>?
    var _launchHereLat: NSNumber?
    var _launchHereLon: NSNumber?
    var _parkHereLat: NSNumber?
    var _parkHereLon: NSNumber?
    var _rigHereLat: NSNumber?
    var _rigHereLon: NSNumber?
    var _seasons: Set<String>?
    var _waterStartHereLat: NSNumber?
    var _waterStartHereLon: NSNumber?
    var _windDirections: Set<String>?
    
    class func dynamoDBTableName() -> String {
        
        return "thekitelife-mobilehub-374752204-spot"
    }
    
    class func hashKeyAttribute() -> String {
        
        return "_id"
    }
    
    class func rangeKeyAttribute() -> String {
        
        return "_title"
    }
    
    override class func jsonKeyPathsByPropertyKey() -> [AnyHashable: Any] {
        return [
            "_id" : "Id",
            "_kiterId" : "kiterId",
            "_title" : "title",
            "_difficulties" : "difficulties",
            "_launchHereLat" : "launchHereLat",
            "_launchHereLon" : "launchHereLon",
            "_parkHereLat" : "parkHereLat",
            "_parkHereLon" : "parkHereLon",
            "_rigHereLat" : "rigHereLat",
            "_rigHereLon" : "rigHereLon",
            "_seasons" : "seasons",
            "_waterStartHereLat" : "waterStartHereLat",
            "_waterStartHereLon" : "waterStartHereLon",
            "_windDirections" : "windDirections",
        ]
    }
}
